#!/bin/bash

echo Copying program to /usr/lib/cgi-bin/
sudo cp myLED.cgi /usr/lib/cgi-bin/
echo Done Copying
echo Now granting +s permissions 
sudo chmod +s /usr/lib/cgi-bin/myLED.cgi
echo Done granting permissions
